### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by mikerockett** [macabeus/vscode-fluent#27] opened 2022-09-07 13:44 UTC
Upon installation of this extension, VSCode’s performance is reduced drastically. Specifically, typing performance goes down the drain, wile everything else remains as snappy as it normally is.

I don’t quite know what could cause this, but I thought it might be the core editor itself for a while, until I remembered that this extension was installed.

Disabling it globally resolved the problem immediately.

I don’t quite know how to debug these kinds of things – happy to help if I can, but would rather just leave it there in case anything springs to your mind as you read this.

Many thanks!

**Comment by macabeus** [comment] 2022-09-07 13:55
Well... I don't know what it could be.

> Specifically, typing performance goes down the drain

There is an early return on the extension only to do the further operations if it's an `ftl` file:

https://github.com/macabeus/vscode-fluent/blob/99d8ddd42ae2c8a3e6a11fcf3fc087139afea87f/src/extension.ts#L38-L41

https://github.com/macabeus/vscode-fluent/blob/99d8ddd42ae2c8a3e6a11fcf3fc087139afea87f/src/utils.ts#L6-L7

Maybe you are using another extension that doesn't work well with this one?
Or it can even be an issue from the new vscode version?

If you could try to open an issue [on vscode repository](https://github.com/microsoft/vscode/issues) and try to debug (I don't know how) it would be very useful.

**Comment by mikerockett** [comment] 2022-09-07 14:21
Thanks for the quick reply @macabeus. I don't know how to debug either, and don't have the time right now to try find out. In the meantime, I'll open an issue on the vscode repo and point it back to this one.

**Comment by mikerockett** [comment] 2022-09-08 04:50
They closed the above issue 😅

I will try and make some time this weekend to debug (after finding out how 🙃).

**Comment by mikerockett** [comment] 2022-09-08 06:32
One thing I did notice is that ripgrep pops up in the process explorer, using a large amount of CPU. The moment I disable the extension, the process is no longer spawned.

**Comment by macabeus** [comment] 2022-09-13 08:31
@mikerockett Thanks for the help.

I'm wondering what could be making the extension floods `ripgrep` processes...

1. is it happen on every file or only when the filename ends with `.ftl`?
2. if you remove the whole `onDidChangeTextDocument` hook on `extension.ts` (lines 38-59), does the issue still happen?
3. likewise the above item, if you remove the call of `updateGlobalState` and/or `updateDiagnosticCollection` within `onDidChangeTextDocument`, does the issue still happen?
4. can you confirm that it doesn't happen when opening a new `.ftl` file?

**Comment by mikerockett** [comment] 2022-09-13 11:16
@macabeus Thanks, I’ll make a little time to help debug this. Where/how exactly do I go about adjusting these files?

**Comment by mikerockett** [comment] 2022-09-13 12:37
@macabeus What I’m asking is how do I get to those files? Is there a specific way to go about modifying installed extensions?

**Comment by macabeus** [comment] 2022-09-13 12:43
Firstly, I would recommend you to uninstall the installed extension (it isn't strictly necessary, but it can be useful to not be confused with the extension being developed and the production one).
Or install [VS Code Insiders](https://code.visualstudio.com/insiders/) to have an isolated VS Code.

Then, you can clone this repository, open it on VS Code/VS Code Insiders, and use the `Run Extension` task to run the develop extension locally.

Note that there is no hot reload. You should run this task again after every change on the extension source code.

Feel free to ask me anything else.

**Comment by mikerockett** [comment] 2022-09-13 12:51
Thanks, sounds easy enough – I'll hop on it now.

**Comment by mikerockett** [comment] 2022-09-13 12:53
Sorry, and to answer your earlier question, it happens when I edit any file, not just `.ftl`s.

**Comment by mikerockett** [comment] 2022-09-13 13:09
I've played with it a bit, and so far, I’ve noticed that this only happens when a workspace is open. If it’s just a folder that’s open, I don't get any rg/ripgrep processes at all.

**Comment by mikerockett** [comment] 2022-09-13 13:15
> if you remove the whole onDidChangeTextDocument hook on extension.ts (lines 38-59), does the issue still happen?

Yes, it does.

**Comment by macabeus** [comment] 2022-09-13 13:26
I guess it could be related to the code action.
VS Code recently made some changes related to code actions, and `vscode-fluent`'s code actions only work on workspace.

Can you comment out `registerCodeActionExtractStringToFluent()` on `extension.ts` and see if it fixes the issue, please?

**Comment by mikerockett** [comment] 2022-09-13 13:32
Your guess appears to be correct – commenting that method call out fixed it.

**Comment by macabeus** [comment] 2022-09-13 13:57
Good!
I really think that it's an issue because of the recent VS Code changes on code actions.

In theory, there is nothing to be done on `vscode-fluent`'s side.

It's an issue on VS Code and should be fixed there.
But since @meganrogge closed the issue, we would need to open a new one being explicit that this extension had no changes in the 11 months and it started to be slow after the new VS Code realease, and it's related to code actions.

But in the meantime, you can try to play with the new code actions API and see if using them fixes this issue.
I didn't check it yet. I don't know how they are and how they can be useful for `vscode-fluent`.

**Comment by mikerockett** [comment] 2022-09-13 14:03
Probably a good idea to open a new issue for this (I was originally thinking of saying that the original issue should be re-opened as this extension is what’s being used to figure out where the problem is). Would you mind opening it, or shall I?

I don't see how code actions could be beneficial to Fluent, at least not for me anyway. I tend to stay far away from code actions and just do my own thing. If corrective action is needed, I do it manually. Same applies to refactoring.

**Comment by macabeus** [comment] 2022-09-13 14:11
> Would you mind opening it, or shall I?

No worries. I can open it today later, after doing a few more tests on it.

Thanks for the help!

**Comment by macabeus** [comment] 2022-09-13 19:48
I opened the issue, and I fixed the tests. It looks like that now VS Code is postponing a little more time to start the extensions on workspace, and I needed to set a timeout now here (see patch below). Probably there are better ways to do it, but it works for now.

If you want to try to fix it, you now have automated tests.
To run it, change the VS Code runner to `Test Extension - With workspace`.

<img width="388" alt="image" src="https://user-images.githubusercontent.com/9501115/189995563-4239c261-51a5-4360-aeb6-56ca2e7d96df.png">

```diff
diff --git a/tests/with-workspace/code-action.test.ts b/tests/with-workspace/code-action.test.ts
index 8bbaa3a..7c009ac 100644
--- a/tests/with-workspace/code-action.test.ts
+++ b/tests/with-workspace/code-action.test.ts
@@ -12,6 +12,8 @@ describe('#Code Action', () => {
           },
         },
         async (mapFilenameToUri) => {
+          await new Promise(r => setTimeout(r, 1000))
+
           const codeActions = await take.codeActions(
             mapFilenameToUri['index.js'],
             new Range(new Position(0, 0), new Position(0, 9))
@@ -33,6 +35,8 @@ describe('#Code Action', () => {
           },
         },
         async (mapFilenameToUri) => {
+          await new Promise(r => setTimeout(r, 1000))
+
           const codeActions = await take.codeActions(
             mapFilenameToUri['index.js'],
             new Range(new Position(0, 0), new Position(0, 9))
@@ -65,6 +69,8 @@ describe('#Code Action', () => {
           },
         },
         async (mapFilenameToUri) => {
+          await new Promise(r => setTimeout(r, 1000))
+
           const codeActions = await take.codeActions(
             mapFilenameToUri['index.js'],
             new Range(new Position(0, 0), new Position(0, 9))
@@ -88,6 +94,7 @@ describe('#Code Action', () => {
             },
           },
           async (mapFilenameToUri) => {
+            await new Promise(r => setTimeout(r, 1000))
             const codeActions = await take.codeActions(
               mapFilenameToUri['index.js'],
               new Range(new Position(0, 0), new Position(0, 9))
@@ -120,6 +127,7 @@ describe('#Code Action', () => {
               },
             },
             async (mapFilenameToUri) => {
+              await new Promise(r => setTimeout(r, 1000))
               const codeActions = await take.codeActions(
                 mapFilenameToUri['index.js'],
                 new Range(new Position(0, 0), new Position(0, 9))
@@ -154,6 +162,7 @@ describe('#Code Action', () => {
                 },
               },
               async (mapFilenameToUri) => {
+                await new Promise(r => setTimeout(r, 1000))
                 const codeActions = await take.codeActions(
                   mapFilenameToUri['index.js'],
                   new Range(new Position(0, 0), new Position(0, 9))
@@ -187,6 +196,7 @@ describe('#Code Action', () => {
                 },
               },
               async (mapFilenameToUri) => {
+                await new Promise(r => setTimeout(r, 1000))
                 const codeActions = await take.codeActions(
                   mapFilenameToUri['index.js'],
                   new Range(new Position(0, 0), new Position(0, 9))
@@ -220,6 +230,7 @@ describe('#Code Action', () => {
                 },
               },
               async (mapFilenameToUri) => {
+                await new Promise(r => setTimeout(r, 1000))
                 const codeActions = await take.codeActions(
                   mapFilenameToUri['index.js'],
                   new Range(new Position(0, 0), new Position(0, 9))
```

**Comment by macabeus** [comment] 2022-09-13 20:21
@mikerockett I opened the issue following your report.

I was trying to reproduce it locally, but I can't. Firstly I tried to reproduce on my macOS, but I can't.
Since you are using Windows, then I opened Parallels, and I can't see VS Code spawning `ripgrep` there as well.

See the video below:

https://user-images.githubusercontent.com/9501115/190001524-5794e3f3-3f0d-4d11-a4fa-7bb053af2f92.mp4

Can you record a video to show me how to reproduce it, please?

**Comment by mikerockett** [comment] 2022-09-14 04:45
@macabeus I’m not running Windows, am on a Mac. I’ll try and record something today.

**Comment by mikerockett** [comment] 2022-09-14 04:53
https://user-images.githubusercontent.com/4586280/190062330-6764da5a-1387-45dd-ab5d-80288b42edf4.mov

The lag between keystrokes is a little difficult to identify from a video, but it is very noticeable when it happens. As you can see, process explorer shows several `rg` processes spawn up and shut down in rapid succession.

**Comment by mikerockett** [comment] 2022-09-14 05:02
And [here’s a video](https://user-images.githubusercontent.com/4586280/190063628-3cf3318a-4884-48ae-a73a-640dd81eb937.mov) with the extension disabled – no `rg` processes, no lag.

**Comment by mikerockett** [comment] 2022-09-14 05:08
I just noticed something:

<img width="600" alt="image" src="https://user-images.githubusercontent.com/4586280/190064364-aa543f8f-852c-4cad-b25b-9e059c3b841d.png">

Notice how the `ftl` extension is not prefixed with `!`, whereas all of the others are. Is it meant to be like that?

**Comment by macabeus** [comment] 2022-10-25 08:33
@mikerockett Well... The issue was closed since the delay in a reply. I'm traveling and I won't have any time soon to do further work now.

If the root of the issue is the `await workspace.findFiles('**/*.ftl')`, in theory, we can avoid it by checking only when a new file is added/removed at the workspace.
If you have time, you can do it.

**Comment by macabeus** [comment] 2022-12-06 09:21
@mikerockett Feel free to one a PR. A kick-start is a good step to deliver a big change later.
I'm not working on this extension anymore, but I can at least try to help you.

> I realised that we actually may need a file-system watcher here to accomodate changes to the workspace that were not done in VSC itself

Did you check about [chokidar](https://github.com/paulmillr/chokidar)?

**Comment by macabeus** [comment] 2024-03-01 10:16
Fixed on https://github.com/macabeus/vscode-fluent/releases/tag/1.0.1

**Closed by macabeus** 2024-03-01 10:16 UTC
